PORT: 5000                                # The server port number
TEST_PORT: <TEST_PORT_NUMBER>                             # Port to run integration tests

SHOW_ERROR_DETAILS: <BOOLEAN>                             # Whether to show technical error details in the response (see RESPONSE_FORMATTING.md for more details)

DATABASE:
  host: localhost                                   # The address or hostname of the database server
  user: postgres                                    # The username to access the database
  password: keith                             # The password associated with the username
  database: user_stories                               # The name of the database to connect to in the system
  port: 5432                                    # The port number used for database connections

AUTH:
  API:
    secretToken: <SECRET_TOKEN>                           # Secret token for API authentication
    authorization: <AUTHORIZATION_KEY>                    # Authorization settings for API
  github:
    clientID: <YOUR CLIENTID>                             # You can find this on your github credentials.
    clientSecret: <YOUR SECRET KEY>                       # You can find this on your github credentials.
    callbackURL: <CALLBACK_URL>                           # You can find this on your github credentials Authorization callback URL.
    passReqToCallback: <PASS_REQ_TO_CALLBACK_OPTION>      # CAN BE SET TO TRUE OR FALSE
    redirectURI: <REDIRECT_URI>                           # You can find this on your github credentials `Homepage URL`.
  google:
    clientID: <YOUR CLIENTID>                             # You can find this on your google credentials (e.g.id.apps.googleusercontent.com).
    clientSecret: <YOUR SECRET KEY>                       # You can find this on your google credentials.
    callbackURL: <CALLBACK_URL>                           # You can find this on your google credentials Authorized redirect URIs.
    passReqToCallback: <PASS_REQ_TO_CALLBACK_OPTION>      # CAN BE SET TO TRUE OR FALSE
    redirectURI: <REDIRECT_URI>                           # You can find this on your google credentials `Authorized JavaScript origins`.
  JWT:
    secret: <YOUR_JWT_SECRET_KEY>                         # JWT secret key. This will be used for creating and decoding tokens
    expiresIn: <EXPIRATION_TIME_OF_TOKEN_IN_SECONDS>      # The expiration time of the token (in seconds)

AWS:
  S3:
    credentials: 
      accessKeyId: <ACCESS_KEY_ID>                        # AWS access key ID for S3 access
      secretAccessKey: <SECRET_ACCESS_KEY>                # AWS secret access key for S3 access
    region: <AWS_REGION>                                  # AWS region for S3

SESSION:
  name: <SESSION_NAME>                                    # Session name
  secret: <SESSION_SECRET_KEY>                            # Session secret key